#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/bryceyxwang/Documents/flutter/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/bryceyxwang/Documents/project/TencentIMFlutterDemo"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/bryceyxwang/Documents/project/TencentIMFlutterDemo/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=U0RLX0FQUElEPTE0MDAxODczNTI=,S0VZPWY0NDJkMGNjYTA2OWJiY2M4Y2VkNTVmNGYxMTNiOTY1OTk5YjkyOGM3OGUzY2Q4MzQ5NTcyODEzM2EwNmY0Y2I=,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/bryceyxwang/Documents/project/TencentIMFlutterDemo/.dart_tool/package_config.json"
